### ISSUE TITLE
Cant sync

### ISSUE THREAD

**Issue by jookk** [daper/nextcloud-passwords-app#6] opened 2018-12-02 11:43 UTC
Newly installed, but it didnt synced / loaded paswords from my server

**Comment by daper** [comment] 2018-12-02 12:18
Can you please tell which version of the app are you using?
Which version of the nextcloud passwords server app have you installed?
Other relevant info like version of nextcloud, php, extensions, etc.

And please can you try this curl command and say if you see any errors?

`curl -u <YOUR NC USER>:<YOUR NC PASSWORD> -X GET 'https://<YOUR NC HOST>/index.php/apps/passwords/api/1.0/password/list' -H 'OCS-APIRequest: true' -d '{ detailLevel: "model+folder" }'`

This is the same call the app uses while getting passwords data.

**Comment by jookk** [comment] 2018-12-02 13:31
App version 1.7
Passwords app on server 2018.11.1 and 2018.12
Nextcloud 14.04
Php 7.2.10

**Comment by daper** [comment] 2018-12-02 19:50
Duplicate of #4. Let's follow up alongside that one.

**Closed by daper** 2018-12-02 19:50 UTC
