### ISSUE TITLE
Some usernames don't sync unless modified from web

### ISSUE THREAD

**Issue by ChameleonScales** [daper/nextcloud-passwords-app#49] opened 2019-11-21 14:05 UTC
Disclaimer: I'm not sure if this is reproducible yet.

One (or at least one) of my usernames was wrong on the mobile version whereas it was correct on both the Nextcloud Passwords web app and Firefox add-on. I unfortunately don't know where this wrong username came from but I found out that the only way to fix it was to change it from the web. Before finding this solution, I tried the following:

- Synchronizing the Android app (Pulling sites)
- Editing the username from the Android app and saving
- Wiping the Android app's cache and data, then uninstalling and reinstalling the app
- Wiping the android device completely and re-flashing Android itself (don't worry I didn't do it just for this purpose)
- testing it on a different Android device

All these attempts showed me the wrong username (including on the other device).

But as soon as I edited this username from the web app, everything went smoothly.

I unfortunately can't give you more detail at the moment and as I said I'm not sure if this can be reproduced or how it could be.

**Comment by daper** [comment] 2020-03-06 00:29
Hi @ChameleonScales, did the username have any special character or something different than the rest? And could you also confirm that this is still happening on the last release?

**Comment by ChameleonScales** [comment] 2020-03-06 11:23
the correct one is only made of digits. I don't remember for the incorrect one because I replaced it a while ago.
So far I haven't encountered this issue again.

**Comment by daper** [comment] 2020-03-06 13:06
Could you check if it would be caused by the same bug as #15 ?

**Comment by ChameleonScales** [comment] 2020-03-07 21:42
Huh... the app indeed crashes when I try to copy that particular digit-only username. It does not have a leading zero as pointed out in the thread though.
However, I realize I spoke too early when saying "everything went smoothly" in my first post because I'm again experiencing the same issue.
The app gives me a completely different username (another set of digits which has nothing in common with the correct one).
The correct username is 4999803349 and the one given by the app is 704836053

**Comment by daper** [comment] 2020-03-08 21:57
Hi @ChameleonScales, I've released a new version v1.13 that fixes #15 too. Could you test if that fixes yours too? The behavior that you describe seems very strange, but let me know. Many thanks!

**Comment by daper** [comment] 2020-03-12 08:31
I am closing this as it looks like it's fixed but feel free to reopen if needed.

**Closed by daper** 2020-03-12 08:31 UTC
Labels: pending to confirm
