### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by paolomeraviglia** [daper/nextcloud-passwords-app#28] opened 2019-05-02 16:15 UTC
Cannot use this app due to Network Error message.

Server: nextcloud 15 with reverse proxy, let's encrypt certificate, TOTP enabled

Tested inserting in the URL string:

http://host.domain/
http://host.domain
https://host.domain/
https://host.domain
host.domain
host.domain:443
host.domain/
localip
http://localip
https://localip/

No Way.

The firefox extension instead is working well

**Comment by GuepardoApps** [comment] 2019-05-02 21:56
Could that be related to #8 ?

I installed it today and receive the same message "network error". Using Logcat I found the error log message "Untrusted chain".

I've installed my nextcloud instance on a raspberry pi and only thing I did to activate SSL was performing following commands:
```
a2ensite default-ssl
service apache2 restart
```

Will investigate that soon, but maybe you can check your Logcat and your setup of the certificate like suggested [here](https://github.com/daper/nextcloud-passwords-app/issues/8#issuecomment-444526057). Will do the same ;)

**Comment by paolomeraviglia** [comment] 2019-05-04 13:25
ok, so

logcat with common cert file from let's encrypt:
```
05-04 14:17:34.761 12380 12460 I WebViewFactory: Loading com.android.chrome version 74.0.3729.136 (code 372913652)
05-04 14:17:34.799  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-04 14:17:34.799  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-04 14:17:34.804  1616  2153 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:17:34.804  1616  2153 D CompatibilityInfo: applicationDensity - 374
05-04 14:17:34.804  1616  2153 D CompatibilityInfo: applicationScale - 1.0
05-04 14:17:34.805 12380 12460 I cr_LibraryLoader: Time to load native libraries: 2 ms (timestamps 1234-1236)
05-04 14:17:34.809 12380 12460 I chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
05-04 14:17:34.809 12380 12460 I cr_LibraryLoader: Expected native library version number "74.0.3729.136", actual native library version number "74.0.3729.136"
05-04 14:17:34.810  1616  8791 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:17:34.810  1616  8791 D CompatibilityInfo: applicationDensity - 374
05-04 14:17:34.810  1616  8791 D CompatibilityInfo: applicationScale - 1.0
05-04 14:17:34.815  1616  8148 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:17:34.815  1616  8148 D CompatibilityInfo: applicationDensity - 374
05-04 14:17:34.815  1616  8148 D CompatibilityInfo: applicationScale - 1.0
05-04 14:17:34.826  1616  8791 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:17:34.826  1616  8791 D CompatibilityInfo: applicationDensity - 374
05-04 14:17:34.826  1616  8791 D CompatibilityInfo: applicationScale - 1.0
05-04 14:17:35.213  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-04 14:17:35.213  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-04 14:17:35.228  1616 11784 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:17:35.228  1616 11784 D CompatibilityInfo: applicationDensity - 374
05-04 14:17:35.229  1616 11784 D CompatibilityInfo: applicationScale - 1.0
05-04 14:17:36.255  1616 11784 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:17:36.256  1616 11784 D CompatibilityInfo: applicationDensity - 374
05-04 14:17:36.256  1616 11784 D CompatibilityInfo: applicationScale - 1.0
05-04 14:17:36.296  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-04 14:17:36.296  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-04 14:17:36.321  1616 11784 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:17:36.321  1616 11784 D CompatibilityInfo: applicationDensity - 374
05-04 14:17:36.322  1616 11784 D CompatibilityInfo: applicationScale - 1.0
05-04 14:17:36.368  2793  2793 D SA.LifecycleCallbacks: time:9893
```

logcat with fullchain.pem
```
05-04 14:21:44.752  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-04 14:21:44.752  1616  1701 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x11 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-04 14:21:44.767  1616  8148 D CompatibilityInfo: mCompatibilityFlags - 0
05-04 14:21:44.767  1616  8148 D CompatibilityInfo: applicationDensity - 374
05-04 14:21:44.767  1616  8148 D CompatibilityInfo: applicationScale - 1.0
05-04 14:21:46.983  8222  8251 I WorkerManager: dispose()
05-04 14:21:48.662  1616  1616 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@41bf914
05-04 14:21:50.157   662   718 E CHRE    : Couldn't connect client socket to 'chre': Connection refused
05-04 14:21:50.157   662   718 W CHRE    : Failed to (re)connect, next try in 300000 ms
```
I'm using nginx as a reverse proxy, the main difference between using fullchain and common cert file is that with fullchain I have no more network error but instead I get "loading" message forever.

**Comment by paolomeraviglia** [comment] 2019-05-11 16:25
Tried the latest build of 5 may on fdroid: nothing new. Still infinite "loading" message

**Comment by daper** [comment] 2019-05-11 17:35
Sorry for the inconveniences guys, but I still not able to reproduce the bug. Let's wait until I can release the debug/logging feature.

**Comment by paolomeraviglia** [comment] 2019-05-11 17:47
yeah, on fdroid is 1.10: do I need to test the google play store app? I can send you in private the domain of my server if you want to test: I can reproduce the issue on every mobile in my house

**Comment by daper** [comment] 2019-05-11 18:06
If we could coordinate for that would be super great. Email me at: david@daper.email.

**Comment by Spiral123456** [comment] 2019-06-06 01:25
Does this happen because of a self-signed cert?

**Comment by michaudg** [comment] 2019-07-14 02:10
Exact same problem here: "infinite loading message" using HAProxy and fullchain Let's Encrypt certificate. Version 1.11.

If I can help, let me know...

**Comment by agolks** [comment] 2019-11-07 22:20
i have letsencrypt certificate and its still happending...

**Comment by daper** [comment] 2020-03-06 00:10
Sorry for my late reply but @agolks could you be not using the full chain certificate therefore it's not validated properly?

For the self-signed certificate you have to include the certification authority on you phone. Maybe this article helps: https://support.google.com/pixelphone/answer/2844832

I am closing the issue, but feel free to reopen if needed.

**Closed by daper** 2020-03-06 00:10 UTC
