### ISSUE TITLE
Stuck on "Loading..." screen in App

### ISSUE THREAD

**Issue by floppyFK** [daper/nextcloud-passwords-app#25] opened 2019-04-11 06:21 UTC
After entering the server-address in the app, it won't get any further than the "Loading..." screen (Same behavior as already described in #3).
I have to delete the android App data after reaching this state, otherwise I won't see the server-address dialog again (btw: I enter the URL including the "https://" prefix). SSL encryption via Lets Encrypt is active.

Is there a way to get some debug output on android? I can't see any activities on the server side at all.

App Version: 1.10
Nextcloud Version: 15.0.7 (Snap install)
Android Version: 9
Server URL: https://nextcloud.[removed].myfritz.net

**Comment by daper** [comment] 2019-04-11 10:03
Hi @floppyFK, really nice description dude, thanks! But sadly it doesn't have any kind of debug right now. Anyways I am working in the new release that will implement it and hope that fixes some bugs already reported. I want to make it for the end of the month, hopefully.

Regarding your issue I can only tell you to ensure that you are using the latest version of [Passwords](https://apps.nextcloud.com/apps/passwords) (nextcloud server app).

**Comment by floppyFK** [comment] 2019-04-11 20:54
Thanks for your quick reply :-)
The used Passwords app was already the latest.

I have created now a second installation of Nextcloud for testing in a VM. But this time i have done a manual installation instead of using the snap package.
Now i can pass the "Loading..." screen. So the problem will probably be some incompatible configuration of the snap package.

**Comment by eglia** [comment] 2019-05-07 08:00
I am having the same problem, but I can't find any useful information in any logs. The only access I see on the server is this:

```
XXX.XXX.XXX.XXX - - [07/May/2019:09:55:26 +0200] "GET /nextcloud/ocs/v1.php/cloud/capabilities HTTP/2.0" 200 223 "-" "okhttp/3.12.1"
```

I already tried the app some time ago and had the same problem. In the meantime, I re-installed my nextcloud instance (for other reasons) and there were updates for the android app & nextcloud app.

I'd really like to use the app, is there anything I can do to provide further information for this issue?

**Comment by daper** [comment] 2019-05-07 10:24
@eglia, I would like to add a logging feature to try to trace all this tricky to reproduce errors. It will come soon, hopefully. Sorry but I cannot help you further.

**Comment by marti28** [comment] 2019-05-16 20:08
@daper If you have a version with debugging or some enabled, please let me know. Would like to help because we encouter the samen error on Android with a Snap package (and Let's Encrypt SSL).

**Comment by Gutz-Pilz** [comment] 2019-07-20 17:34
i have the same issue...
any hints are welcome!

**Comment by Gutz-Pilz** [comment] 2019-07-20 17:47
reinstalled the app. and checked logs while trying to connect with the app.
`172.19.0.9 - "" [20/Jul/2019:17:44:50 +0000] "GET /ocs/v1.php/cloud/capabilities HTTP/1.1" 200 1680 "-" "okhttp/3.12.1"`

thats what appeared - maybe you can use that to find a fix :)

**Comment by pjezusek** [comment] 2019-09-08 14:43
Hello,

is there any update related to this issue? I have the same problem. After entering the server address the application stops on the "Loading..." screen.

Server:
- OS: Alpine LXC container
- Nextcloud version: 16.0.4
- Passwords version: 2019.9.0
- HTTPS: yes, Let's Encrypt
App:
- Nextcloud Passwords version: 1.11
- Android version: 8.0.0

**Comment by lleo19** [comment] 2019-09-11 18:10
Having the same issue here. Nextcloud instance with password app works fine as can add passwords and use browser extensions OK, but android app is stuck on "loading" screen.
The only observation I have to add that on my android device the app is listed with no "permissions requested" in the app settings page, and cannot open that dialog to manually toggle any permissions. Could it be some android permission issue here?
Latest app from f-droid, nextcloud 16.04, latest password NC app.
Lineage OS 16 with microg

**Comment by mtahernia** [comment] 2019-09-18 14:04
Same issue here, Nextcloud instance works fine, the firefox and chrome plugins work fine, but the android app is stuck on the loading screen. Android app is downloaded from google play store and I'm using Nextcloud 16.0.4
My phone is Samsung Galaxy Note 8 running stock android 9 (pie)

**Comment by lleo19** [comment] 2019-09-18 15:52
Were you asked any permissions after install or start?

**Comment by mtahernia** [comment] 2019-09-18 16:27
> 
> 
> Were you asked any permissions after install or start?

No, it did not ask for any permissions, and I checked in the app permissions, and it says "No permissions required"

**Comment by mtahernia** [comment] 2019-09-28 07:57
> > Were you asked any permissions after install or start?
> 
> No, it did not ask for any permissions, and I checked in the app permissions, and it says "No permissions required"

It started working after I upgraded to Nextcloud 16.0.5

**Comment by amsterjanis** [comment] 2020-02-25 11:10
Same problem still here. 
Nextcloud 17.0.3 (same problem was on v16 as well) - Snap install
Nexcloud Passwords app 2020.2.1
Android App 1.11 (same problem is on 1.10 as well) from F-Droid
Android 9 MIUI 11.3.4

**Comment by thrillfall** [comment] 2020-03-05 12:10
the issue is a change in the response for the ocs notification endpoint. The app expects two properties  (which are not there) and fails because there is no error handling for that. As far as i saw those properties are not needed for the app to work. I created a MR to fix this

**Closed** 2020-03-05 21:53 UTC
Labels: bug, good first issue
